"""Shared body mounting elevations and deck boundary, in millimetres."""

from robot_nira import torso_common

SPACER_LENGTH_0_to_1 = 15.0
SPACER_LENGTH_1_to_2 = 32.0
SPACER_LENGTH_TOP = torso_common.SPACER_LENGTH_TOP
# Deliberate raised seating of the removable opening cover.
COVER_SEATING_OFFSET = 0.5
FRONT_DECK_X = 55.0

LAYER_0_BOTTOM = 0.0
LAYER_0_TOP = LAYER_0_BOTTOM + torso_common.THICKNESS
LAYER_1_BOTTOM = LAYER_0_TOP + SPACER_LENGTH_0_to_1
LAYER_1_TOP = LAYER_1_BOTTOM + torso_common.THICKNESS
LAYER_2_BOTTOM = LAYER_1_TOP + SPACER_LENGTH_1_to_2
LAYER_2_TOP = LAYER_2_BOTTOM + torso_common.THICKNESS
LAYER_2_CENTER = (LAYER_2_BOTTOM + LAYER_2_TOP) / 2
LAYER_3_BOTTOM = LAYER_2_TOP + SPACER_LENGTH_TOP
LAYER_3_TOP = LAYER_3_BOTTOM + torso_common.THICKNESS
LAYER_4_BOTTOM = LAYER_3_TOP
SIDE_PLATE_HEIGHT = LAYER_3_TOP - LAYER_1_BOTTOM
DIAGONAL_PLATE_HEIGHT = LAYER_3_TOP - LAYER_2_BOTTOM
COVER_BOTTOM = LAYER_2_BOTTOM + COVER_SEATING_OFFSET
