<?xml version="1.0"?>
<package format="3">
  <name>rumblex_lidar_2d</name>
  <version>0.0.1</version>
  <description>2D lidar integration for RumbleX</description>
  <maintainer email="stein.robotics@gmail.com">christian</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>ydlidar_ros2_driver</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
