<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rumblex_movement</name>
  <version>0.0.1</version>
  <description>Gait controller, kinematics, and movement primitives for the RumbleX hexapod platform</description>
  <maintainer email="stein.robotics@gmail.com">christian</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>ament_index_cpp</depend>
  <depend>rumblex_interfaces</depend>
  <depend>rumblex_utils</depend>
  <depend>nlohmann-json-dev</depend>
  <depend>magic_enum</depend>   # sudo apt install libmagicenum-dev
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
