bno055:
  ros__parameters:
    ros_topic_prefix: "bno055/"
    connection_type: "i2c"
    i2c_bus: 1
    i2c_addr: 0x28
    frame_id: "imu_link"
    data_query_frequency: 10
    calib_status_frequency: 0.1
    placement_axis_remap: "P1"
